on:
  workflow_run:
    workflows: [fork]
    types: [completed]

env:
  ROOT_DIR: "./requests/fork"
  SCRIPTS_DIR: ".github/workflows/scripts"
  GITHUB_ORG: "wayfair-contribs"

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
        echo 'The triggering workflow passed: ${{ steps.fork.outputs.forkUrl }}'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: 📦 move yaml file
        run: ${SCRIPTS_DIR}/move_fork.sh
        shell: bash
      - name: 🗄 push yaml file
        run: ${SCRIPTS_DIR}/push_fork.sh
        shell: bash
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
