---
name: stale

# Identify and close stale issues / PRs
on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.OSPO_API_TOKEN }}
          days-before-stale: 60
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          stale-issue-message: 'тЪая╕П Marking issue as stale due to inactivity'
          stale-pr-message: 'тЪая╕П Marking PR as stale due to inactivity'
          days-before-close: 7
          close-issue-message: 'ЁЯЪл Closing this issue as stale'
          close-pr-message: 'ЁЯЪл Closing this PR as stale'
